# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M.xci
# IP: The module: 'clk_200M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M.xci
# IP: The module: 'clk_200M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/education/no12/week12/dual_cam_display_ov5640_k7/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
