######################################################################
#
# File name : I2C_sim_tb_wave.do
# Created on: Wed May 25 11:00:38 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
