######################################################################
#
# File name : I2C_sim_tb_elaborate.do
# Created on: Tue Sep 19 11:22:51 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.4e\\win64\\vopt -64 +acc=npr -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.I2C_sim_tb xil_defaultlib.glbl -o I2C_sim_tb_opt

quit -force
