######################################################################
#
# File name : I2C_sim_tb_compile.do
# Created on: Tue Sep 19 11:22:39 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.4e\\win64\\vlib questa_lib/work
D:\\questasim64_10.4e\\win64\\vlib questa_lib/msim

D:\\questasim64_10.4e\\win64\\vlib questa_lib/msim/xil_defaultlib
D:\\questasim64_10.4e\\win64\\vlib questa_lib/msim/xpm

D:\\questasim64_10.4e\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib
D:\\questasim64_10.4e\\win64\\vmap xpm questa_lib/msim/xpm

D:\\questasim64_10.4e\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../dual_cam_display_ov5640_k7.srcs/sources_1/imports/sources_1" "+incdir+../../../../dual_cam_display_ov5640_k7.srcs/sources_1/imports/i2c_master" "+incdir+../../../../dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M" \
"D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

D:\\questasim64_10.4e\\win64\\vcom -64 -93 -work xpm  \
"D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \

D:\\questasim64_10.4e\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../dual_cam_display_ov5640_k7.srcs/sources_1/imports/sources_1" "+incdir+../../../../dual_cam_display_ov5640_k7.srcs/sources_1/imports/i2c_master" "+incdir+../../../../dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M" \
"../../../../dual_cam_display_ov5640_k7.srcs/sim_1/new/I2C_sim_tb.v" \

# compile glbl module
D:\\questasim64_10.4e\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

