# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param synth.incrementalSynthesisCache D:/FPGA/week13/7.29/project/dual_cam_display/.Xil/Vivado-14452-LAPTOP-HUGRUEV8/incrSyn
  create_project -in_memory -part xc7k325tffg676-2
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.cache/wt [current_project]
  set_property parent.project_path D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.xpr [current_project]
  set_property ip_repo_paths D:/FPGA/week13/7.29/project/dual_cam_display/usr_IP [current_project]
  update_ip_catalog
  set_property ip_output_repo D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.runs/synth_1/dual_cam_display.dcp
  read_ip -quiet D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/sources_1/ip/afifo_64i_16o_128/afifo_64i_16o_128.xci
  read_ip -quiet D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
  read_ip -quiet D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/sources_1/ip/clk_200M/clk_200M.xci
  read_ip -quiet D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
  read_ip -quiet D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/sources_1/ip/ddr3/ddr3.xci
  read_xdc D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/constrs_1/imports/new/dual_ov5640_an5642_hdmi.xdc
  read_xdc D:/FPGA/week13/7.29/project/dual_cam_display/dual_cam_display_ov5640_k7.srcs/constrs_1/new/dual_cam_display_timming.xdc
  link_design -top dual_cam_display -part xc7k325tffg676-2
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force dual_cam_display_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file dual_cam_display_drc_opted.rpt -pb dual_cam_display_drc_opted.pb -rpx dual_cam_display_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force dual_cam_display_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file dual_cam_display_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file dual_cam_display_utilization_placed.rpt -pb dual_cam_display_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file dual_cam_display_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force dual_cam_display_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file dual_cam_display_drc_routed.rpt -pb dual_cam_display_drc_routed.pb -rpx dual_cam_display_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file dual_cam_display_methodology_drc_routed.rpt -pb dual_cam_display_methodology_drc_routed.pb -rpx dual_cam_display_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file dual_cam_display_power_routed.rpt -pb dual_cam_display_power_summary_routed.pb -rpx dual_cam_display_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file dual_cam_display_route_status.rpt -pb dual_cam_display_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file dual_cam_display_timing_summary_routed.rpt -pb dual_cam_display_timing_summary_routed.pb -rpx dual_cam_display_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file dual_cam_display_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file dual_cam_display_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file dual_cam_display_bus_skew_routed.rpt -pb dual_cam_display_bus_skew_routed.pb -rpx dual_cam_display_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force dual_cam_display_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force dual_cam_display.mmi }
  write_bitstream -force dual_cam_display.bit 
  catch {write_debug_probes -quiet -force dual_cam_display}
  catch {file copy -force dual_cam_display.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

