# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/dual_ov5640_an5642_hdmi.xdc

# IP: ip/afifo_64i_16o_128/afifo_64i_16o_128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_64i_16o_128 || ORIG_REF_NAME==afifo_64i_16o_128} -quiet] -quiet

# IP: ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_16i_64o_512 || ORIG_REF_NAME==afifo_16i_64o_512} -quiet] -quiet
